# Generated by Django 3.0.5 on 2020-12-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20201130_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryhistory',
            name='date',
            field=models.DateField(),
        ),
    ]
