# Generated by Django 3.0.5 on 2020-11-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryhistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
